version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: chatbot-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=llama-3-1-8b-instant
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app

volumes:
  mongo_data:
